// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'vi'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * H​e​l​l​o​ ​{​n​a​m​e​}​!
	 * @param {unknown} name
	 */
	HI: RequiredParams<'name'>
	/**
	 * f​o​l​l​o​w​e​r
	 */
	follower: string
	/**
	 * I​n​t​r​o​d​u​c​t​i​o​n
	 */
	introduction: string
	/**
	 * D​e​s​c​r​i​p​t​i​o​n
	 */
	description: string
	/**
	 * C​o​l​l​e​c​t​i​o​n
	 */
	collection: string
	/**
	 * p​o​s​t​s
	 */
	posts: string
	/**
	 * C​h​e​c​k
	 */
	check: string
}

export type TranslationFunctions = {
	/**
	 * Hello {name}!
	 */
	HI: (arg: { name: unknown }) => LocalizedString
	/**
	 * follower
	 */
	follower: () => LocalizedString
	/**
	 * Introduction
	 */
	introduction: () => LocalizedString
	/**
	 * Description
	 */
	description: () => LocalizedString
	/**
	 * Collection
	 */
	collection: () => LocalizedString
	/**
	 * posts
	 */
	posts: () => LocalizedString
	/**
	 * Check
	 */
	check: () => LocalizedString
}

export type Formatters = {}
