// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'vi'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * f​o​l​l​o​w​e​r
	 */
	follower: string
	/**
	 * I​n​t​r​o​d​u​c​t​i​o​n
	 */
	introduction: string
	/**
	 * D​e​s​c​r​i​p​t​i​o​n
	 */
	description: string
	/**
	 * C​o​l​l​e​c​t​i​o​n
	 */
	collection: string
	/**
	 * p​o​s​t​s
	 */
	posts: string
	/**
	 * c​h​e​c​k
	 */
	check: string
	/**
	 * r​e​s​e​t
	 */
	reset: string
	/**
	 * l​e​a​r​n
	 */
	learn: string
	/**
	 * f​o​l​l​o​w
	 */
	follow: string
	/**
	 * u​n​f​o​l​l​o​w
	 */
	unfollow: string
	/**
	 * L​i​n​k​ ​c​o​p​i​e​d​!
	 */
	linkCopied: string
}

export type TranslationFunctions = {
	/**
	 * follower
	 */
	follower: () => LocalizedString
	/**
	 * Introduction
	 */
	introduction: () => LocalizedString
	/**
	 * Description
	 */
	description: () => LocalizedString
	/**
	 * Collection
	 */
	collection: () => LocalizedString
	/**
	 * posts
	 */
	posts: () => LocalizedString
	/**
	 * check
	 */
	check: () => LocalizedString
	/**
	 * reset
	 */
	reset: () => LocalizedString
	/**
	 * learn
	 */
	learn: () => LocalizedString
	/**
	 * follow
	 */
	follow: () => LocalizedString
	/**
	 * unfollow
	 */
	unfollow: () => LocalizedString
	/**
	 * Link copied!
	 */
	linkCopied: () => LocalizedString
}

export type Formatters = {}
